# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: INFO 

spring:
    profiles:
        active: test 


# ========================
# Application
# ========================
app:
  myVar: ${VAR:defaultValue}
  baseUrlWms: https://geo-i.so.ch/api/wms
  baseUrlFeatureInfo: https://geo-i.so.ch/api/v1/featureinfo/somap?service=WMS&version=1.3.0&request=GetFeatureInfo&x=51&y=51&i=51&j=51&height=101&width=101&srs=EPSG:2056&crs=EPSG:2056&info_format=text%2Fxml&with_geometry=true&with_maptip=false&feature_count=10&FI_POINT_TOLERANCE=8&FI_LINE_TOLERANCE=8&FI_POLYGON_TOLERANCE=4"
  baseUrlBigMap: https://geo-i.so.ch/map/
  backgroundMaps:
    - id: ch.so.agi.hintergrundkarte_sw
      title: Hintergrundkarte schwarz-weiss
      url: https://geo-i.so.ch/api/wmts/1.0.0/{Layer}/default/2056/{TileMatrix}/{TileRow}/{TileCol}
      layer: ch.so.agi.hintergrundkarte_sw 
    - id: ch.so.agi.hintergrundkarte_farbig
      title: Hintergrundkarte farbig    
      url: https://geo-i.so.ch/api/wmts/1.0.0/{Layer}/default/2056/{TileMatrix}/{TileRow}/{TileCol}
      layer: ch.so.agi.hintergrundkarte_farbig 
    - id: ch.so.agi.hintergrundkarte_ortho
      title: Luftbild    
      url: https://geo-i.so.ch/api/wmts/1.0.0/{Layer}/default/2056/{TileMatrix}/{TileRow}/{TileCol}
      layer: ch.so.agi.hintergrundkarte_ortho 
