# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO} 

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:int}
  web:
    resources:
        static-locations: classpath:/launcherDir/,classpath:/public/
    devtools:
        restart:
            additional-exclude: launcherDir/**

management:
    health:
        probes:
            enabled: true
    endpoint:
        health: 
            show-details: always

# ========================
# APPLICATION
# ========================   
lucene:
    queryDefaultRecords: ${LUCENE_QUERY_DEFAULT_RECORDS:10}
    queryMaxRecords: ${LUCENE_QUERY_MAX_RECORDS:50}