FROM alpine:3.16

RUN adduser -S appuser -u 1001

WORKDIR /work/

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/wgc-embedded-server /work/application

EXPOSE 8080
USER 1001

ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
CMD ["./application"]